site_name: MyDocker
site_url: https://centralesupelec.github.io/mydocker/
site_description: Plateforme de TP numériques dans le cloud
site_author: CentraleSupélec

repo_name: CentraleSupelec/mydocker
repo_url: https://github.com/CentraleSupelec/mydocker

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  logo: assets/logo.svg
  favicon: assets/favicon.ico
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - "Présentation": "index.md"
  - "Simple pour l'enseignant": "user_guide.md"
  - "Simple pour l'étudiant": "student_xp.md"
  - "Autres ressources": "other_ressources.md"
