#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE EXTENSION IF NOT EXISTS citext;"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $TEST_DB;
	CREATE DATABASE $TEST_DB;
	GRANT ALL PRIVILEGES ON DATABASE $TEST_DB TO $TEST_DB;
EOSQL
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$TEST_DB" -c "CREATE EXTENSION IF NOT EXISTS citext;"
