stages:
  - build

variables:
  CEPH_VERSION: reef

build:
  stage: build
  image: golang:1.22
  script:
    - apt-get update && apt-get install -yq software-properties-common wget gnupg2
    - bash -c "wget -q -O- 'https://download.ceph.com/keys/release.asc' | apt-key add -"
    - apt-add-repository "deb https://download.ceph.com/debian-$CEPH_VERSION/ $(lsb_release -sc) main"
    - apt-get update && apt-get install -yq libcephfs-dev librbd-dev librados-dev
    - go install -v
  tags:
    - docker
