deployment_enabled=false

debug=false
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thuvtest}
spring.jpa.show-sql=true
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN
logging.level.liquibase=WARN
