version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: thuv
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

  cas:
    image: apereo/cas:7.0.1
    environment:
      CAS_SERVICE_REGISTRY_CORE_INIT_FROM_JSON: "true"
      SERVER_SSL_ENABLED: "false"
    volumes:
      - $PWD/cas-service-1.json:/tmp/cas/cas-service-1.json
    ports:
      - "9443:8443"

  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  db-data:
