version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: npm run start:dev
    volumes:
      - $PWD:/app:rw
      - node_modules:/app/node_modules
    ports:
      - "4200:4200"

volumes:
  node_modules:
    driver: local
