image: golang:1.15

.go_template: &go_template
  stage: build
  tags:
    - docker
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - apt update
    - apt install -y libcephfs-dev librbd-dev librados-dev
    - mkdir -p .go
  cache:
    key: go-path
    paths:
      - .go/pkg/mod/

test:
  <<: *go_template
  script:
    - cd docker-api
    - go test -tags luminous -v -coverprofile=coverage.txt -covermode count
    - go get github.com/boumenot/gocover-cobertura@v1.2.0
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
  only:
    - branches
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: docker-api/coverage.xml
  coverage: '/coverage: \d+\.?\d*% of statements/'

.build_artifacts_template: &build_artifacts_definition
  <<: *go_template
  script:
    - cd docker-api
    - go build -tags luminous

build_uploaded_artifacts:
  <<: *build_artifacts_definition
  artifacts:
    paths:
      - docker-api/docker-api
  only:
    - tags
    - master

build_worthless_artifacts:
  <<: *build_artifacts_definition
  except:
    - tags
    - master

deploy_github:
  image: alpine:3.19.1
  stage: build
  only:
    - tags
  needs:
    - build_uploaded_artifacts
  before_script:
    - apk add zip github-cli
    - zip -r artifacts.zip docker-api/docker-api
  script:
    - gh release --repo CentraleSupelec/mydocker create docker-api-${CI_COMMIT_TAG} --notes ""
    - gh release --repo CentraleSupelec/mydocker upload docker-api-${CI_COMMIT_TAG} artifacts.zip
  tags:
    - docker

stages:
  - test
  - build
