version: '3.8'

services:
  app:
    build:
      context: ./docker
    working_dir: /usr/src/app/docker-api
    volumes:
      - ".:/usr/src/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "gocache:/go/pkg/mod"
    ports:
      - "50000:50000"
# Used to debug with delve
      - "2345:2345"
    command:
      - "bash"
      - "-c"
      - "go build -i -tags luminous && ./docker-api -config-path=.."
# Replace the line above with the line below to debug with delve
#      - "go get github.com/go-delve/delve/cmd/dlv@v1.7.3 && /go/bin/dlv debug --headless --listen=0.0.0.0:2345 --api-version=2 --accept-multiclient --build-flags='-i -tags luminous' -- -config-path=.."

volumes:
  gocache:
