version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - "gocache:/go/pkg/mod"
      - "$PWD:/app:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "50000:50000"
# Used to debug with delve
      - "2345:2345"
# Uncomment the two lines below to debug with delve
    # command:
    #  - "go get github.com/go-delve/delve/cmd/dlv@v1.7.3 && /go/bin/dlv debug --headless --listen=0.0.0.0:2345 --api-version=2 --accept-multiclient --build-flags='-i -tags luminous' -- -config-path=.."

volumes:
  gocache:
