version: '3.8'
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    deploy:
      replicas: 1
    ports:
      - 80:80
      - 443:443
      - 2019:2019
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - caddy-overlay

networks:
  caddy-overlay:
    external: true
